* cl-skeleton

=cl-skeleton= is my personal project template for Common Lisp.

No fancy stuff and template engines, just plain old shell script and
=envsubst(1)=.

The generated Common Lisp system includes a main ASDF system
definition, a test system definition, scripts for running the tests,
Dockerfiles for ECL, CCL and SBCL implementations and Github Actions
for building Docker images and running the test suite of the project.

* Usage

Clone the repo.

#+begin_src shell
  git clone https://github.com/dnaeon/cl-skeleton.git
#+end_src

Navigate to the repo you've just cloned and edit the
=project-vars.env= file.

#+begin_src shell
  cd cl-skeleton
  # Edit project-vars.env file
#+end_src

Once ready with the changes, execute the following command which will
set things up for you. You need to provide a path for your Common Lisp
project. For example, if your new project will reside in
=~/Projects/lisp/cl-foobar= you would execute this command.

#+begin_src shell
  ./build-skeleton.sh expand ~/Projects/lisp/cl-foobar
#+end_src

Review the generated files, initialize a new Git repo and commit.

#+begin_src shell
  cd ~/Projects/lisp/cl-foobar
  git init && git add . && git commit -m 'Initial commit'
#+end_src

* Contributing

=cl-skeleton= is hosted on [[https://github.com/dnaeon/cl-skeleton][Github]]. Please contribute by reporting
issues, suggesting features or by sending patches using pull requests.

* Authors

- Marin Atanasov Nikolov <[[mailto:dnaeon@gmail.com][dnaeon@gmail.com]]>

* License

This project is Open Source and licensed under the [[http://opensource.org/licenses/BSD-2-Clause][BSD License]].
